module.exports = [
    {
        item_name: "Bi-weekly Pay",
        amount: 4000.00,
        date: '2022-6-1',
        from: "Google",
        category: "Income",
    },
    {
        item_name: "Veterinarian Visit",
        amount: -200.00,
        date: '2022-6-7',
        from: "Queens Vet Clinic",
        category: "Pet Expenses",
    },
    {
        item_name: "Phone Payment",
        amount: -250.00,
        date: '2022-6-10',
        from: "T-mobile",
        category: "Payments",
    },
    {
        item_name: "Car Insurance",
        amount: -294.67,
        date:  '2022-6-14',
        from: "Progressive Insurance",
        category: "Car Expenses",
    },
    {
        item_name: "Monthly Savings Transfer",
        amount: -500.00,
        date: '2022-6-15',
        from: "Citibank",
        category: "Savings",
    },
    {
        item_name: "Bi-weekly Pay",
        amount: 4000.00,
        date: '2022-6-15',
        from: "Google",
        category: "Income",
    },
    {
        item_name: "Gas",
        amount: -150.00,
        date: '2022-6-17',
        from: "National Grid",
        category: "Payments",
    },
    {
        item_name: "Electric",
        amount: -200.00,
        date: '2022-6-19',
        from: "ConEdison",
        category: "Payments",
    },
    {
        item_name: "New Desk (Wooden)",
        amount: -256.30,
        date: '2022-6-27',
        from: "Ikea",
        category: "Misc. House Expenses",
    },
    {
        item_name: "Credit Card Payment",
        amount: -478.84,
        date: '2022-6-30',
        from: "Amex",
        category: "Payments",
    },
    {
        item_name: "Bi-weekly Pay",
        amount: 4000.00,
        date: '2022-7-1',
        from: "Google",
        category: "Income",
    },
    {
        item_name: "Monthly Groceries",
        amount: -562.10,
        date: '2022-7-2',
        from: "Costco",
        category: "Food",
    },
]