module.exports = [
    {
        item_name: "Bi-weekly Pay",
        amount: 4000.00,
        date: '2022-06-01',
        from: "Google",
        category: "Income",
    },
    {
        item_name: "Veterinarian Visit",
        amount: -200.00,
        date: '2022-06-07',
        from: "Queens Vet Clinic",
        category: "Expense",
    },
    {
        item_name: "Phone Payment",
        amount: -250.00,
        date: '2022-06-10',
        from: "T-mobile",
        category: "Expense",
    },
    {
        item_name: "Car Insurance",
        amount: -294.67,
        date:  '2022-06-14',
        from: "Progressive Insurance",
        category: "Expense",
    },
    {
        item_name: "Monthly Savings Transfer",
        amount: -500.00,
        date: '2022-06-15',
        from: "Citibank",
        category: "Expense",
    },
    {
        item_name: "Bi-weekly Pay",
        amount: 4000.00,
        date: '2022-06-15',
        from: "Google",
        category: "Income",
    },
    {
        item_name: "Gas",
        amount: -150.00,
        date: '2022-06-17',
        from: "National Grid",
        category: "Expense",
    },
    {
        item_name: "Electric",
        amount: -200.00,
        date: '2022-06-19',
        from: "ConEdison",
        category: "Expense",
    },
    {
        item_name: "New Desk (Wooden)",
        amount: -256.30,
        date: '2022-06-27',
        from: "Ikea",
        category: "Expense",
    },
    {
        item_name: "Credit Card Payment",
        amount: -478.84,
        date: '2022-06-30',
        from: "Amex",
        category: "Expense",
    },
    {
        item_name: "Bi-weekly Pay",
        amount: 4000.00,
        date: '2022-07-01',
        from: "Google",
        category: "Income",
    },
    {
        item_name: "Monthly Groceries",
        amount: -562.10,
        date: '2022-07-02',
        from: "Costco",
        category: "Expense",
    },
]